### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sescandell** [brainsonic/AzureDistributionBundle#5]
Some changes have been made to be compaible with Symfony changes and Azure changes and are not documented.
Also, some extra functionnalities have been added and should be documented.

**Comment by smashou** [comment]
Hi, Is this project still active ?

**Comment by sescandell** [comment]
Yes it is.

For information, the `dev` branch is the more up to date.

**Comment by smashou** [comment]
Ok, great, Thanks !

**Comment by RuslanZavacky** [comment]
is it still alive? :)

**Comment by sescandell** [comment]
Yes, planned commit : moving on latest Azure SDK

**Comment by sescandell** [comment]
Done
